injectEnvironmentFiles:
   - .pipes.env
yarnPath: .yarn/releases/yarn-4.0.0-rc.47.cjs
npmScopes:
  island-is:
    npmAlwaysAuth: true
nmMode: hardlinks-local
nodeLinker: node-modules
npmScopes: { island-is: { npmRegistryServer: "https://npm.pkg.github.com" } }
