name: 'Get Cache Keys'
description: 'Action to get cache'
inputs:
  enable-cache:
    description: 'Enable cache'
    default: ''
  keys:
    description: 'Keys'
    default: 'false'
  cypress-path:
    description: 'Path to cypress'
    default: '/github/home/.cache/Cypress'
outputs:
  keys:
    description: 'Keys'
    value: ${{ steps.get-cache-keys.outputs._CACHE_KEYS }}
runs:
  using: 'composite'
  steps:
    - uses: cue-lang/setup-cue@v1.0.1
    - name: Generate Dynamic Steps
      id: prepare
      shell: bash
      env:
        ENABLE_CACHE: ${{ inputs.enable-cache }}
        CYPRESS_PATH: ${{ inputs.cypress-path }}
        YAML_FILE: ./.tmp-dynamic-cache/action.yml
      run: |
        node scripts/ci/cache/generate-cache-steps.mjs
    - name: Run cache workflow
      id: run-cache
      uses: ./.tmp-dynamic-cache
    - name: Cleanup cache workflow
      shell: bash
      run: rm -rf ./.tmp-dynamic-cache
    - name: Cache actions
      id: cache-actions
      shell: bash
      env:
        ENABLE_CACHE: ${{ inputs.enable-cache }}
        CYPRESS_PATH: ${{ inputs.cypress-path }}
        _CACHE_KEYS: ${{ steps.prepare.outputs._CACHE_KEYS }}
        _INIT_CACHE: ${{ steps.prepare.outputs._INIT_CACHE }}
      run: |
        node ./scripts/ci/cache/cache-action.mjs
